= Pattern: Builder Pattern
:source-highlighter: highlight.js
Anıl Şenocak <senocakanil@gmail.com>
2.0, April 16, 2024
:description: To provide a flexible solution to various object creation problems in oop.
:organization: Personal
:doctype: book
:preface-title: Preface
// Settings:
:experimental:
:reproducible:
:icons: font
:listing-caption: Listing
:sectnums:
:toc:
:toclevels: 3
:xrefstyle: short
:nofooter:
// URIs:
:url-quickref: https://github.com/senocak/tutorials/tree/master/

[%notitle]
--
[abstract]
{description}
--

== Açıklama
Bazen projelerimizde nesnelerimize ait birçok özellik olabilir ve bu nesnelerimizi farklı farklı özellikler ile  oluşturmak isteriz. Dolayısıyla bazen çalıştığımız sınıflar içerisinde çok fazla parametre alan metodlar ve yapılandırıcılar kullanabiliyoruz. Bu kullanılabilirliği ve okunabilirliği oldukça zorlaştıran bir durum. Bazen aynı methodu çok fazla kez overload edip, kendimize iş yükü doğurabiliyoruz.

== Örnek
[source,kotlin]
----
class Araba private constructor(
    val marka: String,
    val model: String,
    val yil: Int,
    val renk: String,
    val beygir: Int
) {
    internal class Builder {
        private lateinit var marka: String
        private lateinit var model: String
        private var yil: Int = 0
        private lateinit var renk: String
        private var beygir: Int = 0

        fun marka(marka: String) = apply { this.marka = marka }
        fun model(model: String) = apply { this.model = model }
        fun yil(yil: Int) = apply { this.yil = yil }
        fun renk(renk: String) = apply { this.renk = renk }
        fun beygir(beygir: Int) = apply { this.beygir = beygir }

        fun build(): Araba =
            require(value = yil > 0) { "Yıl zorunlu" }
                .run { Araba(marka = marka, model = model, yil = yil, renk = renk, beygir = beygir) }
    }
    override fun toString(): String = "Araba(marka='$marka', model='$model', yil=$yil, renk='$renk', beygir=$beygir)"
}
----
[source,kotlin]
----
fun main() {
    Araba.Builder()
        .marka("Toyota")
        .model("Camry")
        .yil(2022)
        .renk("Red")
        .beygir(203)
        .build()
        .also { println(message = it) }
    // Araba(marka='Toyota', model='Camry', yil=2022, renk='Red', beygir=203)
}
----

== Uygulanabilirlik
- Karmaşık bir nesne oluşturma algoritması, nesneyi oluşturan parçalardan ve bunların nasıl birleştirildiğinden bağımsız olmalıdır.
- Yapım süreci, inşa edilen nesne için farklı temsillere izin vermelidir.

== Örnekleri
- java.lang.StringBuilder
- java.nio.ByteBuffer(FloatBuffer, IntBuffer ve benzeri gibi benzer arabelleklerin yanı sıra.)
- java.lang.StringBuffer
- java.lang.Appendable'in tüm implementleri
- Apache Camel builders
- Apache Commons Option.Builder

link:examples/src/main/kotlin/com/github/senocak/blog/builder-pattern.kt[builder-pattern.kt]
