= Java: Intermediate Operations
:source-highlighter: highlight.js
Anıl Şenocak <senocakanil@gmail.com>
2.0, April 16, 2024
:description:  Ara işlevler bir akışı geri döndürür. Tüm intermediate işlemleri tembeldir, bu nedenle gerçekten bir işlemin sonucu gerekli olana kadar yürütülmezler.
:organization: Personal
:doctype: book
:preface-title: Preface
// Settings:
:experimental:
:reproducible:
:icons: font
:listing-caption: Listing
:sectnums:
:toc:
:toclevels: 3
:xrefstyle: short
:nofooter:

[%notitle]
--
[abstract]
{description}
--

== filter()
Belirli bir Tahminle(Predicate) eşleşen bir akışın öğelerini filtrelememize izin veren Stream interface'ini implement etmiş bir intermediate ara işlemidir, verilen input ile eşleşen akışın öğelerinden oluşan bir akış döndürür.
[source,kotlin]
----
fun main() {
    mutableListOf(20, 12, 4, 6, 2, 20)
        .apply {
            this.stream().filter { it > 9 }.toList().also { println(message = "collect: $it") } // collect: [20, 12, 20]
        }
}
----
== map()
Verilen işlevin bu stream öğelerine uygulanmasının sonuçlarından oluşan bir stream döndürür.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().map { it + 1}.collect(Collectors.toList()).also { println(message = "map: $it") } // map: [4, 5, 7, 13, 21]
        }
}
----
Burada map fonksiyonu, Function türünden değişken alır. Fonksiyon, functional interface'dir ve bir apply() metoduna sahiptir. Bu yöntem bir değer alır ve başka bir değer döndürür.  map() sarmalayıcı türleri de ara intermediate oprerasyon kategorisine girer.

`mapToDouble()` `mapToLong()` `mapToInt()` gibi türleri de implement edilmiştir.

== flatMap()
Bir koleksiyon listesi için en iyi sonucu verir. Örneği iki listeyle ve bunların flatmap() yöntemini kullanarak tek bir akışa nasıl dönüştürüleceğini göstereceğiz.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().map { "$it+${it + 1}" }.flatMap { line -> Stream.of(line.split('+')) }.toList().also { println(message = "flatMap: $it") } // flatMap: [[3, 4], [4, 5], [6, 7], [12, 13], [20, 21]]
        }
}
----
`flatMapToInt()` `flatMapToLong()` `flatMapToDouble()` gibi türleri de implement edilmiştir.

== distinct()
Bu akışın farklı öğelerinden (Object.equals(Object)'e göre) oluşan bir akış döndürür.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20, 20)
        .apply {
            this.stream().distinct().toList().also { println(message = "distinct: $it") } // distinct: [3, 4, 6, 12, 20]
        }
}
----

== sorted()
Doğal sıraya göre sıralanmış bu akışın öğelerinden oluşan bir akış döndürür. Bu akışın öğeleri Comparable değilse, terminal işlemi yürütüldüğünde bir java.lang.ClassCastException oluşturulabilir.

TIP: Sıralı akışlar için sıralama sabittir. Sırasız akışlar için kararlılık garantisi verilmez.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20, 20)
        .apply {
            this.stream().distinct().toList().also { println(message = "distinct: $it") } // distinct: [3, 4, 6, 12, 20]
        }
}
----

== peek()
Bu akışın öğelerinden oluşan bir akış döndürür, ayrıca elde edilen akıştan öğeler tüketilirken her öğe üzerinde sağlanan eylemi gerçekleştirir. peek() yöntemi, Java 8'deki akışlarda hata ayıklamanın en iyi yoludur.

TIP: stream pipeline için peek() çağırma sırasını tahmin edemeyiz.
[source,kotlin]
----
fun main() {
    mutableListOf("Ornek", "stream", "sort")
        .apply {
            this.stream().filter { it.length > 2 }.peek { print("peek: $it,") }.map { it.uppercase() }.toList() // peek: Ornek,peek: stream,peek: sort,
        }
}
----

== limit()
Verilen sınırlı boyutta bir akış döndürür. Akıştan kalan öğeleri kesecektir.

TIP: limit() sıralı akışlar için uygundur ve paralel akışlar için iyi performans sonuçları veremez.
[source,kotlin]
----
fun main() {
    mutableListOf("Ornek", "stream", "sort")
        .apply {
            this.stream().limit(2).toList().also { println(message = "limit: $it") } // limit: [Ornek, stream]
        }
}
----

== skip()
Verilen n öğesini atlar ve bir Stream döndürür. Bu, bir Liste'de veya Akıştaki son n kayıt'ta veya satır üzerinde herhangi bir işlem yapmak istediğinizde en kullanışlı olanıdır.
[source,kotlin]
----
fun main() {
    mutableListOf("Ornek", "stream", "sort")
        .apply {
            this.stream().skip(2).toList().also { println(message = "skip: $it") } // skip: [sort]
        }
}
----