= Kotlin: Regex
:source-highlighter: highlight.js
Anıl Şenocak <senocakanil@gmail.com>
2.0, April 16, 2024
:description: Düzenli ifadeler
:organization: Personal
:doctype: book
:preface-title: Preface
// Settings:
:experimental:
:reproducible:
:icons: font
:listing-caption: Listing
:sectnums:
:toc:
:toclevels: 3
:xrefstyle: short
:nofooter:
// URIs:
:url-quickref: https://github.com/senocak/tutorials/tree/master/

[%notitle]
--
[abstract]
{description}
--

== Açıklama
Metinde arama yapmak için kullanılan bir metin kalıbıdır.

Örneğin, bir string'te e-posta adresleri, URL'ler, telefon numaraları, tarihler vb. için aramak için normal bir ifade kullanabilirsiniz. Bu, Dize ile farklı normal ifadeleri eşleştirerek yapılabilir.

- true / false: Normal ifadenin metinle eşleşip eşleşmediğini belirtir.
- Bir eşleşme kümesi: Metinde bulunan normal ifadenin her oluşumu için bir eşleşme.

== Core Sınıfları
- Pattern (kotlin.text.Pattern)
- Extension function `String.toRegex()` (kotlin.text)

Pattern sınıfı, pattern(normal ifadeler) oluşturmak için kullanılır. Bir kalıp, kendisini bir metinle eşleştirebilen, nesne biçiminde önceden derlenmiş düzenli ifadedir.

[source,kotlin]
----
val regex1 = Regex(pattern = "a[bc]+d?")
val regex2 = "a[bc]+d?".toRegex()
val regex3 = Regex.fromLiteral(literal = "a[bc]+d?")
val regex4 = """a[bc]+d?\W""".toRegex()
----

== Matching Options
Hem Regex hemde toRegex methodları aşağıdaki matching opsiyonlarını uygulayabilir
[source,kotlin]
----
val regex1 = Regex("a(b|c)+d?", RegexOption.CANON_EQ)
val regex2 = Regex("a(b|c)+d?", setOf(RegexOption.DOT_MATCHES_ALL, RegexOption.COMMENTS))
val regex3 = "a(b|c)+d?".toRegex(option = RegexOption.MULTILINE)
val regex4 = "a(b|c)+d?".toRegex(options = setOf(RegexOption.IGNORE_CASE, RegexOption.COMMENTS, RegexOption.UNIX_LINES))
----

== Matching
Hem Regex hemde toRegex methodları aşağıdaki matching opsiyonlarını uygulayabilir
[source,kotlin]
----
fun main() {
    val regex = """a([bc]+)d?""".toRegex()
    println(message = regex.containsMatchIn(input = "xabcdy")) // true
    println(message = regex.matches(input = "abcd")) // true
    println(message = regex matches "xabcdy") // false

    var matchResult = regex.matchEntire(input = "abbccbbd")
    println(message = matchResult?.value) // abbccbbd
    matchResult = regex.find(input = "abcbabbd")
    println(message = matchResult?.value) // abcb
    val matchResults = regex.findAll(input = "abcb abbd")
    matchResults.toList().forEach { print(message = "${it.value},") } // abcb,abbd,
}
----

== Sınırlar
Bir dizgedeki sınırları(boundaries) da eşleştirebiliriz. Sınır, bir dizenin başı, bir dizenin sonu, bir kelimenin başlangıcı vb. olabilir.

|===
|Sembol |Açıklama

| ^	 |  Satırın başlangıcı
| $	 |  Satırın sonu
| \b |  Bir kelime sınırı (bir kelimenin başladığı veya bittiği yer, örneğin boşluk, sekme vb.).
| \B | 	Sözcük olmayan bir sınır.
| \A | 	Girişin başlangıcı
| \G | 	Önceki eşleşmenin sonu
| \Z | 	Girişin sonu, ancak son sonlandırıcı için (varsa).
| \z |  Satır Başı (veya Dize)

|===

== Java Interoperability
Düzenli ifademizi Java koduna veya `java.util.regex.Pattern` örneğini bekleyen başka bir JVM dili API'sine aktarmamız gerekirse, Regex'imizi kolayca dönüştürebiliriz

[source,kotlin]
----
fun main() {
    val pattern: Pattern = """a([bc]+)d?""".toPattern()
}
----

== Örnekler
[source,kotlin]
----
private fun matching() {
    println(message = "-------------------------Matching")
    val regex = """a([bc]+)d?""".toRegex()
    println(message = regex.containsMatchIn(input = "xabcdy")) // true
    println(message = regex.matches(input = "abcd")) // true
    println(message = regex matches "xabcdy") // false
}
private fun extractMatching() {
    val regex = """a([bc]+)d?""".toRegex()
    println(message = "-------------------------Extracting Matching Components")
    var matchResult = regex.matchEntire(input = "abbccbbd")
    println(message = matchResult?.value) // abbccbbd
    matchResult = regex.find(input = "abcbabbd")
    println(message = matchResult?.value) // abcb
    val matchResults = regex.findAll(input = "abcb abbd")
    println(message = matchResults.toList().map { it.value }) // [abcb, abbd]
}
private fun matchResult() {
    println(message = "-------------------------The MatchResult Class")
    val regex = """a([bc]+)d?""".toRegex()
    val matchResult = regex.find(input = "abcb abbd")
    println(message = "abcb" == matchResult?.value) // true
    println(message = IntRange(0, 3) == matchResult?.range) // true
}
private fun groupsAndDestructuring() {
    println(message = "-------------------------Groups and Destructuring")
    var regex = """a([bc]+)d?""".toRegex()
    var matchResult = regex.find(input = "abcb abbd")
    println(message = listOf("abcb", "bcb") == matchResult?.groupValues) // true
    println(message = IntRange(1, 3) == matchResult!!.groups[1]?.range) // true

    regex = """([\w\s]+) is (\d+) years old""".toRegex()
    matchResult = regex.find(input = "Mickey Mouse is 95 years old")!!
    val (name, age) = matchResult.destructured
    println(message = "Mickey Mouse" == name) // true
    println(message = "95" == age) // true
}
private fun captureGroupsByName() {
    println(message = "-------------------------Capture Groups by Name")
    val regex = """(?<name>[\w\s]+) is (?<age>\d+) years old""".toRegex()
    val matchResult = regex.find(input = "Mickey Mouse is 95 years old")!!

    val age = matchResult.groups["age"]?.value!!
    val name = matchResult.groups["name"]?.value!!

    println(message = "Mickey Mouse" == name) // true
    println(message = "95" == age) // true
}
private fun multipleMatches() {
    println(message = "-------------------------Multiple Matches")
    val regex = """a([bc]+)d?""".toRegex()
    var matchResult = regex.find(input = "abcb abbd")

    println(message = "abcb" == matchResult!!.value) // true

    matchResult = matchResult.next()
    println(message = "abbd" == matchResult!!.value) // true

    matchResult = matchResult.next()
    println(message = matchResult) // null
}
private fun replacing() {
    println(message = "-------------------------Replacing")
    val regex = """(red|green|blue)""".toRegex()
    val beautiful = "Roses are red, Violets are blue"
    val grim = regex.replace(input = beautiful, replacement = "dark")
    println(message = "Roses are dark, Violets are dark" == grim) // true

    val shiny = regex.replaceFirst(input = beautiful, replacement = "rainbow")
    println(message = "Roses are rainbow, Violets are blue" == shiny) // true
}
private fun complexReplacements() {
    println(message = "-------------------------Complex Replacements")
    val regex = """(red|green|blue)""".toRegex()
    val beautiful = "Roses are red, Violets are blue"
    val reallyBeautiful = regex.replace(input = beautiful) { "${it.value.uppercase()}!" }
    println(message = "Roses are RED!, Violets are BLUE!" == reallyBeautiful) // true
}
private fun splitting() {
    println(message = "-------------------------Splitting")
    val regex = """\W+""".toRegex()
    val beautiful = "Roses are red, Violets are blue"
    println(message = listOf("Roses", "are", "red", "Violets", "are", "blue") == regex.split(input = beautiful)) // true
}
fun main() {
    matching()
    extractMatching()
    matchResult()
    groupsAndDestructuring()
    captureGroupsByName()
    multipleMatches()
    replacing()
    complexReplacements()
    splitting()

}
----