= Java: Terminal Operations
:source-highlighter: highlight.js
Anıl Şenocak <senocakanil@gmail.com>
2.0, April 16, 2024
:description: Bir terminal işlemi Stream başlatır ve Stream ardışık düzenine ve içeriğine bağlı bir sonuç döndürür.
:organization: Personal
:doctype: book
:preface-title: Preface
// Settings:
:experimental:
:reproducible:
:icons: font
:listing-caption: Listing
:sectnums:
:toc:
:toclevels: 3
:xrefstyle: short
:nofooter:

[%notitle]
--
[abstract]
{description}
--

== allMatch()
Akıştaki tüm öğeler sağlanan bir yüklemle eşleşirse true döndürür, aksi takdirde false döndürür. Bu bir kısa devre terminal işlemidir, çünkü eşleşmeyen herhangi bir eleman bulunursa işlem hemen durur (tıpkı AND operatörünün kısa devre davranışı gibi).
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().allMatch { n: Int -> n % 3 == 0 }.also { println(message = "allMatch: $it") } // allMatch: false
        }
}
----

== anyMatch()
Akıştaki herhangi bir öğe sağlanan bir değer ile eşleşirse true döndürür.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().anyMatch { n: Int -> n % 3 == 0 }.also { println(message = "anyMatch: $it") } // anyMatch: true
        }
}
----

== noneMatch()
Akıştaki hiçbir öğe sağlanan bir değer ile eşleşmezse true değerini döndürür.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().noneMatch { n: Int -> n % 21 == 0 }.also { println(message = "noneMatch: $it") } // anyMatch: true
        }
}
----

== collect()
Bir akıştaki öğeleri koleksiyon gibi bir kapsayıcıda toplar. İşlenmiş değerin ArrayList gibi değişken bir sonuç kapsayıcısı olduğu değişken azaltma işlemini gerçekleştirir. Bu yöntem, yararlı azaltma işlemleri sağlayan bir Collector uygulaması alır. Collectors sınıfı, JDK'da yaygın bir uygulamadır.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().allMatch { n: Int -> n % 3 == 0 }.also { println(message = "allMatch: $it") } // allMatch: false
            this.stream().anyMatch { n: Int -> n % 3 == 0 }.also { println(message = "anyMatch: $it") } // anyMatch: true
            this.stream().noneMatch { n: Int -> n % 21 == 0 }.also { println(message = "noneMatch: $it") } // anyMatch: true
            this.stream().filter { it > 9 }.collect(Collectors.toList()).also { println(message = "collect: $it") } // collect: [12, 20]
        }
}
----

== count()
Akıştaki toplam öğe sayısını döndürür.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().count().also { println(message = "count: $it") } // count: 3
        }
}
----

== forEach()
Akıştaki her öğe için bir eylem gerçekleştirir.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().forEach { x: Int -> print(message = "$x,") } // 3,4,6,12,20,
        }
}
----

== max()
Sağlanan karşılaştırıcıya göre akıştaki maxiumum öğeyi döndüren özel bir azaltma işlemidir.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().max { x: Int, y: Int -> x.compareTo(other = y) }.get().also { println(message = "max: $it") } // max: 20
        }
}
----

== reduce()
Akıştaki her öğeye bir ikili işleç uygular; burada işleç için ilk argüman önceki uygulamanın dönüş değeridir ve ikinci argüman geçerli akış öğesidir. Sağlanan karşılaştırıcıya göre akıştaki maxiumum öğeyi döndüren özel bir azaltma işlemidir.
[source,kotlin]
----
fun main() {
    mutableListOf(3, 4, 6, 12, 20)
        .apply {
            this.stream().reduce { x: Int, y: Int -> if (x < y) x else y }.ifPresent { println(message = "reduce: $it") } // reduce: 3
        }
}
----

== Örnek
[source,kotlin]
----
import java.util.stream.Collectors
import java.util.stream.Stream

fun main() {
    mutableListOf(20, 12, 4, 6, 2, 20).apply {
        this.stream().allMatch { it % 3 == 0 }.also { println(message = "allMatch: $it") } // allMatch: false
        this.stream().anyMatch { it % 3 == 0 }.also { println(message = "anyMatch: $it") } // anyMatch: true
        this.stream().noneMatch { it % 21 == 0 }.also { println(message = "noneMatch: $it") } // anyMatch: true
        this.stream().filter { it > 9 }.collect(Collectors.toList()).also { println(message = "collect: $it") } // collect: [12, 20]
        this.stream().count().also { println(message = "count: $it") } // count: 3
        this.stream().max { x: Int, y: Int -> x.compareTo(other = y) }.get().also { println(message = "max: $it") } // max: 20
        this.stream().reduce { x: Int, y: Int -> if (x < y) x else y }.ifPresent { println(message = "reduce: $it") } // reduce: 3
        this.stream().map { it + 1}.toList().also { println(message = "map: $it") } // map: [4, 5, 7, 13, 21]
        this.stream().map { "$it+${it + 1}" }.flatMap { line -> Stream.of(line.split('+')) }.toList().also { println(message = "flatMap: $it") } // flatMap: [[3, 4], [4, 5], [6, 7], [12, 13], [20, 21]]
        this.stream().distinct().toList().also { println(message = "distinct: $it") } // distinct: [3, 4, 6, 12, 20]
        this.stream().forEach { print(message = "$it,") } // 3,4,6,12,20,
    }
    mutableListOf("Ornek", "stream", "sort").apply {
        this.stream().sorted().toList().also { println(message = "sorted: $it") } // sorted: [Ornek, sort, stream]
        this.stream().limit(2).toList().also { println(message = "limit: $it") } // limit: [Ornek, stream]
        this.stream().skip(2).toList().also { println(message = "skip: $it") } // skip: [sort]
        this.stream().filter { it.length > 2 }.peek { print("peek: $it,") }.map { it.uppercase() }.toList() // peek: Ornek,peek: stream,peek: sort,
    }
}
----