= Testcontainers / PostgreSQL, MySQL, MariaDB, Redis, RabbitMq
:source-highlighter: highlight.js
Anıl Şenocak <senocakanil@gmail.com>
2.0, April 16, 2024
:description: Testcontainers, Docker konteynerlerini JUnit testlerine kolaylıkla entegre etmeye izin veren bir Java kütüphanesidir.
:organization: Personal
:doctype: book
:preface-title: Preface
// Settings:
:experimental:
:reproducible:
:icons: font
:listing-caption: Listing
:sectnums:
:toc:
:toclevels: 3
:xrefstyle: short
:nofooter:

[%notitle]
--
[abstract]
{description}
--
== Bağımlılıklar
Testcontainers'ı kullanmak için aşağıdaki bağımlılıkları pom.xml'e eklenmeli (Maven tabanlı proje varsayılarak):
[source, xml]
----
<properties>
    <org.testcontainers.version>1.12.5</org.testcontainers.version>
</properties>

<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>testcontainers</artifactId>
    <version>${org.testcontainers.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>${VERİTABANI}</artifactId>
    <version>${org.testcontainers.version}</version>
    <scope>test</scope>
</dependency>
----
VERİTABANI, postgresql, mysql, mariadb'den biridir.

TIP: Testcontainers, JUnit 5 (Jupiter) eklentisi sağlar, ancak bu eklentide sunulan senaryoda gerekli olmayacaktır.

== Veri Kaynağı Yapılandırması
Spring Boot testleri için Testcontainers'ı yapılandırma adımları:

Driver'ı Testcontainers JDBC proxy sürücüsü olan org.testcontainers.jdbc.ContainerDatabaseDriver olarak ayarlanmalı. Bunun amacı veri kaynağı başlatıldığında gerekli Docker konteynerini başlatmaktan sorumlu olacaktır.
Veritabanınız için diyalekti açıkça ayarlanmalı aksi takdirde uygulamayı başlatırken hata alırız. Uygulamada JPA kullandığınızda bu adım gereklidir.(Spring Data JPA aracılığıyla)
JDBC URL'sini jdbc:tc:<database-image>:<version>:/// olarak ayarlanmalı böylece Testcontainers hangi veritabanı görüntüsünü kullanacağını bilir.
PostgreSQL yapılandırması:
[source, yaml]
----
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:9.6:///
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
----
MySQL yapılandırması:
[source, yaml]
----
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
----
MariaDB yapılandırması:
[source, yaml]
----
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.3:///
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
----
Veritabanı yapılandırması hakkında daha fazla bilgiyi link:https://www.testcontainers.org/modules/databases/[burada] bulunabilir.

== Test veritabanını Testcontainers ile başlatma
Veritabanını Testcontainers tarafından yüklenen komut dosyasıyla başlatabilirsiniz. Dosya, doğrudan sınıf yolundan veya herhangi bir konumdan yüklenebilir. Yapılacak tek şey, JDBC URL'sini değiştirmektir:

[source, yaml]
----
spring:
  datasource:
    url: jdbc:tc:postgresql:9.6:///?TC_INITSCRIPT=file:src/main/resources/init_db.sql
    #url: jdbc:tc:postgresql:9.6:///?TC_INITSCRIPT=classpath:init_db.sql
----

== @DataJpaTest
TC'yi @DataJpaTest'te kullanmak için, uygulama tanımlı (otomatik yapılandırılmış) veri kaynağının kullanıldığından emin olmanız gerekir. Testinize, aşağıda gösterildiği gibi @AutoConfigureTestDatabase ile açıklama ekleyerek bunu kolayca yapabilirsiniz:
[source, java]
----
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
public class OwnerRepositoryTests {

    @Autowired
    private OwnerRepository ownerRepository;

    @Test
    void findAllReturnsJohnDoe() { // as defined in tc-initscript.sql
        var owners = ownerRepository.findAll();
        assertThat(owners.size()).isOne();
        assertThat(owners.get(0).getFirstName()).isEqualTo("John");
        assertThat(owners.get(0).getLastName()).isEqualTo("Doe");
    }
}
----

== @SpringBootTest
Testlerimizde kullanılacak ApplicationContext'i oluşturarak çalışır. Çalışma ortamımızı yapılandırmak için @SpringBootTest'in webEnvironment niteliğini kullanabiliriz; kapsayıcının mock bir sunucu uygulaması ortamında çalışması için burada WebEnvironment.MOCK kullanıyoruz.

Uygulama tanımlı veri kaynağını kullanır, bu nedenle ek değişiklik gerekmez.

[source, java]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
public class OwnerResourceTests {
    @MockBean UserRepository mockRepository;
    @Autowired WebApplicationContext wac;

    @Test
    void findAllReturnsJohnDoe() throws Exception {
        given().webAppContextSetup(wac)
        .when().get("/owners")
        .then().status(HttpStatus.OK)
               .body("_embedded.owners.firstName", containsInAnyOrder("John"),
                     "_embedded.owners.lastName", containsInAnyOrder("Doe"));
    }

    @Test
    public void givenCountMethodMocked_WhenCountInvoked_ThenMockValueReturned() {
        Mockito.when(mockRepository.count()).thenReturn(123L);

        UserRepository userRepoFromContext = wac.getBean(UserRepository.class);
        long userCount = userRepoFromContext.count();

        Assert.assertEquals(123L, userCount);
        Mockito.verify(mockRepository).count();
    }
}
----

=== Mock Mvc ile Controller Metotlarının Test Edilmesi
Spring Boot classpath’de Servlet API sınıfları mevcut ise default olarak Mock nesnelerden oluşan bir Servlet Container ortamı oluşturmaktadır.

Bu ortam üzerinden Tomcat gibi herhangi bir web container olmaksızın MVC controller metotları entegrasyon testlerine tabi tutulabilir

TIP: `AutoConfigureMockMvc` MockMvc'yi yapılandırmak istediğimizde kullanırız. MockMvc ile ilgili tüm otomatik yapılandırmayı etkinleştirir.

=== @MockBean Annotation
Spring uygulama bağlamına mock nesneler eklemek için @MockBean kullanabiliriz. Mock nesne, uygulama bağlamında aynı türden herhangi bir mevcut bean'nin yerini alacaktır.

Aynı türden bir bean tanımlanmamışsa, yeni bir tane eklenecektir. Bu açıklama, belirli bir bean'nin mock edilmesi gereken entegrasyon testlerinde kullanışlıdır.

Annotation'ı bir alanda kullandığımızda, uygulama bağlamında kayıtlı olmanın yanı sıra, sahte alana da enjekte edilecektir. Bu, yukarıdaki kodda belirgindir.

Burada, count yöntemini saplamak için enjekte edilen UserRepository mock'unu kullandık. Daha sonra, gerçekten mock bean olduğunu doğrulamak için uygulama bağlamındaki bean'i kullandık.

== Testcontainer manuel configuration
Aşağıdaki örnek SpringBoot 3.2.2 ve Kotlin ile yapılmıştır.

=== Dependency'ler
[source, kotlin]
----
testImplementation("org.testcontainers:junit-jupiter")
testImplementation("org.springframework.boot:spring-boot-testcontainers")
testImplementation("org.testcontainers:postgresql")
----

=== PostgresqlInitializer
[source, kotlin]
----
@TestConfiguration
class PostgresqlInitializer : ApplicationContextInitializer<ConfigurableApplicationContext> {
    override fun initialize(configurableApplicationContext: ConfigurableApplicationContext) {
        TestPropertyValues.of(
            "spring.datasource.url=" + CONTAINER.jdbcUrl,
            "spring.datasource.username=" + CONTAINER.username,
            "spring.datasource.password=" + CONTAINER.password
        ).applyTo(configurableApplicationContext.environment)
    }

    companion object {
        @Container private var CONTAINER: PostgreSQLContainer<*> = PostgreSQLContainer("postgres:14")
            //.withExposedPorts(3306)
            .withDatabaseName("spring")
            .withUsername("postgres")
            .withPassword("secret")
            .withInitScript("db.sql")
            .withStartupTimeout(TestConstants.CONTAINER_WAIT_TIMEOUT)
            .withCreateContainerCmdModifier { cmd: CreateContainerCmd -> cmd.withName("SQL_CONTAINER") }

        init {
            CONTAINER.start()
        }
    }
}
----

=== RabbitMqInitializer
[source, kotlin]
----
@TestConfiguration
class RabbitMqInitializer : ApplicationContextInitializer<ConfigurableApplicationContext> {
    override fun initialize(configurableApplicationContext: ConfigurableApplicationContext) {
        val host: String = CONTAINER.host
        val port: Int = CONTAINER.getMappedPort(RABBIT_MQ_PORT)
        TestPropertyValues.of(
                "spring.rabbitmq.host=$host",
                "spring.rabbitmq.port=$port",
                "spring.rabbitmq.user=guest",
                "spring.rabbitmq.password=guest"
            )
            .applyTo(configurableApplicationContext.environment)
    }

    companion object {
        private const val RABBIT_MQ_PORT = 5672

        @Container private var CONTAINER: GenericContainer<*> = GenericContainer("rabbitmq:3.6-management-alpine")
            .withExposedPorts(RABBIT_MQ_PORT)
            .withEnv("RABBITMQ_IO_THREAD_POOL_SIZE", "4")
            .withStartupTimeout(TestConstants.CONTAINER_WAIT_TIMEOUT)
            .waitingFor(Wait.forListeningPort())

        init {
            CONTAINER.start()
        }
    }
}
----

=== RedisInitializer
[source, kotlin]
----
@TestConfiguration
class RedisInitializer : ApplicationContextInitializer<ConfigurableApplicationContext> {
    private lateinit var jedis: Jedis

    override fun initialize(configurableApplicationContext: ConfigurableApplicationContext) {
        val host: String = CONTAINER.host
        val port: Int = CONTAINER.firstMappedPort
        TestPropertyValues.of(
            "REDIS_HOST=$host",
            "REDIS_PORT=$port",
            "REDIS_PASSWORD=" + "",
        ).applyTo(configurableApplicationContext.environment)

        jedis = Jedis(host, port)
        assertEquals("PONG", jedis.ping())
        setInitialValuesRedis()
    }

    private fun setInitialValuesRedis() {
        jedis.configSet("notify-keyspace-events", "KEA")
        val emailConfig: MutableMap<String, String> = HashMap()
        emailConfig["protocol"] = "protocol"
        emailConfig["host"] = "host"
        emailConfig["port"] = "port"
        emailConfig["from"] = "from"
        emailConfig["password"] = "password"
        jedis.hmset("email", emailConfig)
    }

    companion object {

        @Container private var CONTAINER: GenericContainer<*> = GenericContainer("redis:6.2-alpine")
            .withExposedPorts(6379)
            .withStartupTimeout(TestConstants.CONTAINER_WAIT_TIMEOUT)
            .waitingFor(Wait.forLogMessage(".*Ready to accept connections.*", 1))
            .withReuse(true)

        init {
            CONTAINER.start()
        }
    }
}
----

=== SpringBootTestConfig custom annotation
[source, kotlin]
----
@Tag("integration")
@Target(AnnotationTarget.ANNOTATION_CLASS, AnnotationTarget.CLASS)
@ExtendWith(SpringExtension::class)
@Retention(AnnotationRetention.RUNTIME)
@ActiveProfiles(value = ["integration-test"])
@TestClassOrder(ClassOrderer.OrderAnnotation::class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@ContextConfiguration(initializers = [
    PostgresqlInitializer::class,
    RabbitMqInitializer::class,
    RedisInitializer::class
])
annotation class SpringBootTestConfig
----

==== Target
Annotation kullanım aralığını ayarlar ve ElementType'a göre açıklama kullanılabilir aralığının numaralandırma kümesini belirtir.

    ElementType.ANNOTATION_TYPE, annotation'ın @interface tarafından yazıldığını, aksi takdirde bir hata bildirildiğini belirtir. Benzer şekilde, yaygın olarak kullanılan ElementType.METHOD, açıklamanın metod olduğu anlamına gelir, aksi takdirde bir hata bildirilir.

ElementType:

|===
|Tip|Annotation scope

|TYPE|Sınıf, interface veya enum bildirimi
|FIELD|Alan bildirimleri ve enum sabitleri
|METHOD|method
|PARAMETER|parametre
|CONSTRUCTOR|Construction metod
|LOCAL_VARIABLE|Local değişken
|ANNOTATION_TYPE|Annotation tipi (@interface tarafından değiştirilen tür)
|PACKAGE|Kurulum paketi beyanı
|TYPE_PARAMETER|Tip parametresi bildirimi
|TYPE_USE|Tek tip kullan

|Column 1, row 1
|===

==== Retention
RetentionPolicy enum türünün sabitiyle birlikte, yorumun ne kadar süreyle tutulması gerektiğini belirtir.  RetentionPolicy yorumları tutmak için çeşitli stratejileri açıklar.

|===
||Açıklama
|SOURCE|Derleyici yorumu drop eder.
|CLASS|Derleyici dosyada günlüğe kaydedilir ve varsayılan çalışma zamanı sanal makine saklaması gerektirmez.
|RUNTIME|Derleyici bir dosyaya kaydedilir ve kolay okuma için sanal makine çalışma zamanı tarafından tutulur.

|Column 1, row 1
|===

==== ActiveProfiles
Spring integration testinde ApplicationContext'i yüklerken profilleri etkinleştirmek için kullanılan sınıf düzeyinde bir açıklamadır. Aşağıdaki özellikleri vardır.

profiles: Etkinleştirilecek profilleri belirtir.
resolver: Profilleri programlı olarak etkinleştirmek için ActiveProfilesResolver'ı belirtir.
value: profiles öğesinin takma adıdır
inheritProfiles: Etkin profillerin üst sınıftan devralınıp devralınmayacağına karar veren Boolean değeridir. Varsayılan değeri true.

==== @ContextConfiguration:
Spring entegrasyonu testi için bir ApplicationContext yükler. ApplicationContext'i XML kaynağı veya @Configuration ile açıklamalı JavaConfig kullanarak yükleyebilir. Ayrıca @Component, @Service, @Repository vb. ile açıklamalı bir bileşenleri yükleyebilir. Ayrıca javax.inject ile anootated edilmiş sınıfları da yükleyebiliriz. Aşağıdaki öğelere sahiptir.

- `classes` @Configuration ile tanımlanmış sınıflar, ApplicationContext'i yüklemek için atanır.
- `inheritInitializers` Test üst sınıflarından bağlam başlatıcıların devralınıp devralınmayacağına karar veren bir Boolean değeri. Varsayılan true
- `inheritLocations` Test üst sınıflarından resource konumlarının veya annotate edilmiş sınıfların devralınıp devralınmayacağına karar veren Boolean değeri. Varsayılan true
- `initializers` ConfigurableApplicationContext'i başlatan uygulama bağlamı başlatıcı sınıflarını belirtiriz.
- `loader` ApplicationContext'i yüklemek için ContextLoader veya SmartContextLoader sınıfımızı belirtiyoruz.
- `locations` ApplicationContext'i yüklemek için resource konumlarını belirtiriz.
- `name` Bu konfigürasyon tarafından temsil edilen bağlam hiyerarşi seviyesinin adıdır.
- `value` locations öğesinin diğer adıdır.

=== Testing
[source, kotlin]
----
@SpringBootTestConfig
class AuthControllerIT {
    @Autowired private lateinit var authController: AuthController
    @Autowired private lateinit var objectMapper: ObjectMapper
    @Autowired private lateinit var userService: UserService
    @Autowired private lateinit var emailActivationTokenService: EmailActivationTokenService
    @Autowired private lateinit var messageSourceService: MessageSourceService
    @Autowired private lateinit var passwordResetTokenRepository: PasswordResetTokenRepository

    private lateinit var mockMvc: MockMvc

    @BeforeEach
    fun beforeEach() {
        mockMvc = MockMvcBuilders.standaloneSetup(authController)
            .setControllerAdvice(RestExceptionHandler(messageSourceService = messageSourceService))
            .build()
        passwordResetTokenRepository.deleteAll()
    }

    private val request: LoginRequest = LoginRequest(email = "", password = "")

    @Test
    fun given_whenLogin_thenReturn200() {
        // Given
        request.email = "anil1@senocak.com"
        request.password = "stanford.Pollich14"
        // When
        val perform: ResultActions = MockMvcRequestBuilders
            .post("${BaseController.V1_AUTH_URL}/login")
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(loginRequest))
            .run { mockMvc.perform(request) }
        // Then
        perform
            .andExpect(MockMvcResultMatchers.status().isOk)
            .andExpect(MockMvcResultMatchers.jsonPath("$.user.email", equalTo(request.email)))
            .andExpect(MockMvcResultMatchers.jsonPath("$.user.roles", hasSize<Any>(1)))
            .andExpect(MockMvcResultMatchers.jsonPath("$.user.roles[0].name", equalTo(RoleName.ROLE_ADMIN.role)))
            .andExpect(MockMvcResultMatchers.jsonPath("$.token", IsNull.notNullValue()))
    }
}
----
